export default subjects = [
    "C Programming(PSIPL)",
    "Digital Systems and Microprocessors(DSM)",
    "OOPS in Java",
    "Probability and Statistics",
    "Computer Organization and Architecture(COA)",
    "Database Management System(DBMS)",
    "Data Structures and Competitive Programming(DS-CP)",
    "Discrete Structures and Graph Theory(DSGT)",
    "Linear Algebra(LA)",
    "Design And Analysis Of Algorithms(DAA)",
    "Computer Communication and Networks(CCN)",
    "Operating Systems(OS)",
    "Theory of Computation(TOC)",
    "Software Engineering(SE)",
    "Artificial Intelligence and Machine Learning(AIML)",
    "Distributed Computing(DC)",
    "Cloud and Information Technology(CITL)",
    "System Programming and Compiler Construction(SPCC)",
    "Fundamentals of Signal and Image Processing(FOSIP)",
    "Blockchain Technology(BCT)",
    "Ethical Hacking(EH)",
    "Big Data Analytics(BDA)",
    "Cryptography and System Security(CSS)",
    "Artificial Intelligence for Healthcare Analytics(AIH)",
    "Advanced Data Visualization(ADV)",
    "Consumer Electronics(CE)",
    "Design Thinking, Innovation and Creativity"
  ];
  
