const BigDataAnalyticsBDA1 = [
  {
    question: "Which of the following is NOT a core characteristic of Big Data?",
    options: ["Variety", "Veracity", "Velocity", "Validation"],
    correct: 3,
    category: "BDA"
  },
  {
    question: "Which data warehousing technique is most suitable for handling massive datasets with high velocity?",
    options: ["OLTP", "OLAP", "Data Lake", "Data Mart"],
    correct: 2,
    category: "BDA"
  },
  {
    question: "What is the primary function of a MapReduce framework in Big Data processing?",
    options: ["Data visualization", "Data cleaning", "Data aggregation", "Parallel data processing"],
    correct: 3,
    category: "BDA"
  },
  {
    question: "A company wants to analyze customer purchasing patterns across different product categories. Which Big Data tool is most appropriate for this task?",
    options: ["Hadoop", "Tableau", "Spark", "Hive"],
    correct: 2,
    category: "BDA"
  },
  {
    question: "Which technique is used to discover hidden patterns in large datasets?",
    options: ["Regression analysis", "Clustering", "Classification", "Data mining"],
    correct: 3,
    category: "BDA"
  },
  {
    question: "What is the key difference between a data lake and a data warehouse?",
    options: ["Data lakes are structured, data warehouses are unstructured", "Data lakes are schema-on-read, data warehouses are schema-on-write", "Data lakes are for ad-hoc queries, data warehouses are for predefined queries", "Data lakes are smaller, data warehouses are larger"],
    correct: 1,
    category: "BDA"
  },
  {
    question: "In a social media analysis project, which method is best for identifying influential users?",
    options: ["Sentiment analysis", "Topic modeling", "Network analysis", "Regression analysis"],
    correct: 2,
    category: "BDA"
  },
  {
    question: "What is the role of NoSQL databases in Big Data Analytics?",
    options: ["Data normalization", "Relational database management", "Handling semi-structured and unstructured data", "Data validation"],
    correct: 2,
    category: "BDA"
  },
  {
    question: "Which algorithm is commonly used for anomaly detection in time series data?",
    options: ["K-means", "Linear regression", "Isolation forest", "Decision tree"],
    correct: 2,
    category: "BDA"
  },
  {
    question: "Which technique is suitable for identifying trends in sales data over time?",
    options: ["Association rule mining", "Time series analysis", "Clustering", "Classification"],
    correct: 1,
    category: "BDA"
  },
  {
    question: "Which technology is widely used for real-time stream processing in Big Data?",
    options: ["Spark Streaming", "Hive", "Pig", "MapReduce"],
    correct: 0,
    category: "BDA"
  },
  {
    question: "What is a key challenge in integrating data from diverse sources in Big Data?",
    options: ["Data validation", "Data transformation", "Data quality", "Data security"],
    correct: 1,
    category: "BDA"
  },
  {
    question: "Which tool is typically used for exploratory data analysis (EDA) in Big Data?",
    options: ["Apache Spark", "Tableau", "Hadoop", "Hive"],
    correct: 1,
    category: "BDA"
  },
  {
    question: "Which programming language is commonly used for developing Big Data applications?",
    options: ["Python", "Java", "Scala", "All of the above"],
    correct: 3,
    category: "BDA"
  },
  {
    question: "What is a key component of a distributed file system for Big Data storage?",
    options: ["Data warehouse", "Relational database", "Data mart", "HDFS"],
    correct: 3,
    category: "BDA"
  },
  {
    question: "Which technology is critical for handling data in the petabyte or exabyte range?",
    options: ["Data mining", "Machine learning", "Cloud computing", "Data visualization"],
    correct: 2,
    category: "BDA"
  },
  {
    question: "What is a crucial aspect of data governance in Big Data projects?",
    options: ["Data quality", "Data privacy", "Data security", "All of the above"],
    correct: 3,
    category: "BDA"
  },
  {
    question: "Which metric assesses the effectiveness of a recommendation system in Big Data?",
    options: ["Precision", "Recall", "F1-score", "All of the above"],
    correct: 3,
    category: "BDA"
  },
  {
    question: "Which type of data analysis is most suited for understanding customer behavior patterns?",
    options: ["Descriptive analytics", "Predictive analytics", "Prescriptive analytics", "Diagnostic analytics"],
    correct: 0,
    category: "BDA"
  },
  {
    question: "What is a primary concern when dealing with data breaches in Big Data systems?",
    options: ["Data accuracy", "Data security", "Data volume", "Data variety"],
    correct: 1,
    category: "BDA"
  },
  {
    question: "Which approach is used to manage the large volumes of data generated by sensors?",
    options: ["Data warehousing", "Data streaming", "Data mining", "Data visualization"],
    correct: 1,
    category: "BDA"
  },
  {
    question: "Which model is particularly useful for understanding the relationship between multiple variables in Big Data?",
    options: ["Decision tree", "Logistic regression", "Clustering", "Association rule"],
    correct: 1,
    category: "BDA"
  },
  {
    question: "What is the main advantage of using cloud platforms for Big Data storage and processing?",
    options: ["Lower capital expenditure", "Scalability", "Accessibility", "All of the above"],
    correct: 3,
    category: "BDA"
  },
  {
    question: "Which data warehousing technique is best suited for handling massive datasets that need to be analyzed on a frequent basis for real-time insights?",
    options: ["Data Mart", "Data Lakehouse", "OLAP Cube", "Relational Database"],
    correct: 1,
    category: "BDA"
  },
  {
    question: "In a Hadoop ecosystem, which component is responsible for managing the storage and retrieval of data across numerous commodity servers?",
    options: ["MapReduce", "HDFS", "YARN", "Pig"],
    correct: 1,
    category: "BDA"
  },
  {
    question: "Which algorithm is commonly used for anomaly detection in massive datasets, leveraging the principle of clustering?",
    options: ["Linear Regression", "Decision Trees", "K-Means Clustering", "Naive Bayes"],
    correct: 2,
    category: "BDA"
  },
  {
    question: "A company wants to analyze customer purchasing patterns over the last five years.  Which data integration method is most appropriate for combining data from various disparate databases?",
    options: ["ETL", "Data Mining", "Data Visualization", "Machine Learning"],
    correct: 0,
    category: "BDA"
  },
  {
    question: "Which approach is best for identifying and understanding hidden patterns and relationships in large datasets of social media interactions?",
    options: ["Regression Analysis", "Network Analysis", "Sentiment Analysis", "Clustering"],
    correct: 1,
    category: "BDA"
  },
  {
    question: "A streaming data analytics platform needs to process billions of events per second. Which concept is crucial for efficient processing in this environment?",
    options: ["Batch Processing", "Real-time Processing", "Data Warehousing", "ETL"],
    correct: 1,
    category: "BDA"
  },
  {
    question: "Which technique is commonly employed for handling missing values in a dataset used for machine learning models in BDA?",
    options: ["Interpolation", "Imputation", "Aggregation", "Normalization"],
    correct: 1,
    category: "BDA"
  },
  {
    question: "What is the primary purpose of a data pipeline in a Big Data environment?",
    options: ["Data visualization", "Data storage", "Data transformation and movement", "Data analysis"],
    correct: 2,
    category: "BDA"
  },
  {
    question: "Which Spark programming paradigm is suitable for processing large-scale graph datasets?",
    options: ["Spark SQL", "Spark Streaming", "GraphX", "MLlib"],
    correct: 2,
    category: "BDA"
  },
  {
    question: "In a social media analysis project, which metric helps assess the spread of information or influence within a network?",
    options: ["Engagement Rate", "Reach", "Retweet Ratio", "Centrality"],
    correct: 3,
    category: "BDA"
  },
  {
    question: "Which characteristic is crucial for a data storage system designed to handle a rapidly growing volume of data?",
    options: ["Scalability", "Consistency", "Security", "Accuracy"],
    correct: 0,
    category: "BDA"
  },
  {
    question: "What is the key difference between a data lake and a data warehouse?",
    options: ["Data lakes are structured, data warehouses are unstructured", "Data warehouses are optimized for analytical queries, data lakes are not", "Data lakes contain raw data, data warehouses contain processed data", "Data lakes are typically smaller, data warehouses are typically larger"],
    correct: 2,
    category: "BDA"
  },
  {
    question: "Which tool is commonly used for visualizing complex relationships within a dataset in a Big Data context?",
    options: ["Tableau", "Power BI", "Qlik Sense", "All of the above"],
    correct: 3,
    category: "BDA"
  },
  {
    question: "What is a common challenge in managing large-scale, distributed datasets?",
    options: ["Data consistency", "Data quality", "Data security", "Data storage and retrieval efficiency"],
    correct: 3,
    category: "BDA"
  },
  {
    question: "A company uses Spark to process large amounts of log data to identify unusual patterns. Which Spark module is most helpful?",
    options: ["Spark SQL", "MLlib", "GraphX", "Spark Streaming"],
    correct: 3,
    category: "BDA"
  },
  {
    question: "What does ACID properties in the context of database transactions refer to?",
    options: ["Atomic, Consistent, Isolated, Duplicate", "Atomic, Consistent, Isolated, Durable", "Accurate, Consistent, Integrated, Durable", "Asynchronous, Consistent, Independent, Durable"],
    correct: 1,
    category: "BDA"
  },
  {
    question: "Which key performance indicator (KPI) is crucial for assessing the responsiveness of a real-time data processing system?",
    options: ["Data Accuracy", "Latency", "Throughput", "Data Completeness"],
    correct: 1,
    category: "BDA"
  },
  {
    question: "Which tool is crucial for performing large-scale statistical analysis in a Big Data context?",
    options: ["R", "Python", "SAS", "All of the above"],
    correct: 3,
    category: "BDA"
  },
  {
    question: "In data warehousing, what does ETL stand for?",
    options: ["Extract, Transfer, Label", "Extract, Transform, Load", "Export, Transfer, Label", "Extract, Translate, Load"],
    correct: 1,
    category: "BDA"
  },
  {
    question: "How does NoSQL differ from SQL databases in terms of data modeling?",
    options: ["NoSQL uses schemas, SQL uses schemas", "NoSQL uses schemas, SQL uses flexible models", "NoSQL uses flexible models, SQL uses schemas", "NoSQL doesn't use schemas, SQL uses schemas"],
    correct: 2,
    category: "BDA"
  },
  {
    question: "What is the primary function of a data lakehouse?",
    options: ["Data integration", "Data warehousing", "Data storage and processing", "Data visualization"],
    correct: 2,
    category: "BDA"
  },
  {
    question: "Which method is used to measure the effectiveness of different data mining models?",
    options: ["Cross-validation", "Data cleaning", "Data transformation", "Data visualization"],
    correct: 0,
    category: "BDA"
  },
  {
    question: "What is a common technique used to ensure data quality in large datasets?",
    options: ["Data mining", "Data scrubbing", "Data aggregation", "Data visualization"],
    correct: 1,
    category: "BDA"
  },
  {
    question: "Which type of data analysis focuses on identifying trends and patterns in historical data?",
    options: ["Predictive analysis", "Prescriptive analysis", "Descriptive analysis", "Exploratory analysis"],
    correct: 2,
    category: "BDA"
  },
  {
    question: "What is the primary function of a data mart?",
    options: ["Store raw data", "Provide data for specific business units", "Process large volumes of data in real time", "Analyze data from multiple sources"],
    correct: 1,
    category: "BDA"
  },
  {
    question: "Which data warehousing technique is best suited for handling a large volume of semi-structured data from diverse sources in a Big Data environment?",
    options: ["Star Schema", "Snowflake Schema", "Dimensional Modeling", "Columnar Database"],
    correct: 3,
    category: "BDA"
  },
  {
    question: "A company wants to identify customer segments based on purchasing patterns across various online channels. Which Big Data analytics technique would be most appropriate?",
    options: ["Clustering", "Classification", "Regression", "Association Rule Mining"],
    correct: 0,
    category: "BDA"
  }
];

export default BigDataAnalyticsBDA1;
